### ISSUE TITLE
line numbers in light mode are hard to read

### ISSUE THREAD

**Issue by gauteh** [reedes/vim-colors-pencil#24] opened 2017-06-22 09:38 UTC
Would it be possible to increase the contrast on the line numbers in light mode?

**Comment by reedes** [comment] 2017-08-05 22:48
They're low contrast by design, to reduce distraction. 

If you don't mind getting into the code, modify your local copy of colors/pencil.vim. Search for LineNr.

**Comment by zackhsi** [comment] 2018-05-18 17:01
This is especially pronounced inside tmux. I'm curious why the colors are different in tmux (happy to open a separate issue).

non-tmux left, tmux right
<img width="1679" alt="screen shot 2018-05-18 at 10 00 17 am" src="https://user-images.githubusercontent.com/806101/40247771-57aa5488-5a82-11e8-9ec0-d002fc60455e.png">

**Comment by markand** [comment] 2018-05-19 12:57
If oyu use truecolors you may need additional tweaks in both .vimrc and .tmux.conf though.

**Comment by markand** [comment] 2018-12-21 15:52
Would you mind adding an option to tweak line number contrast?

**Comment by daliusd** [comment] 2020-11-09 10:02
I would close this as well. It is working fine in tmux for me on Mac OS X and Ubuntu. I think there must be configuration issue on reported side.

**Comment by alerque** [comment] 2020-11-09 10:19
Also confirmed seems fine to me in `tmux`, please open a new issue if there is still a problem with this plugin.

**Closed by alerque** 2020-11-09 10:19 UTC
